### PR TITLE
Symlink update script not working in Ubuntu

### PR DESCRIPTION
**Pull request by juchong**
The shell script would skip over both cases because the if statement was looking for a file. Adding the configuration file fixed the issue. Tested in Ubuntu 14.04

### CODE REVIEW

**Comment by sten0** [comment]
Btrfsmaintenance has been packaged for Debian and is currently waiting for ftp-masters to push it to the archive.  After the next release I plan to upload to unstable, where Ubuntu will automatically sync it for their next release.  Ubuntu often syncs packages from experimental, so if someone makes it a priority then the current version could be in either this spring's or next fall's official release.  Having more people test the package will help it to transition more quickly to Debian stable :-)

https://ftp-master.debian.org/new/btrfsmaintenance_0.3.1-1~exp1.html

**Comment by kdave** [comment]
Is this fix still need on debian/ubuntu? It changes the path from `/etc/sysconfig/btrfsmaintenance` to `/etc/sysconfig/btrfsmaintenance/sysconfig.btrfsmaintenance`, which would not work on openSUSE (and maybe others).

**Comment by kdave** [comment]
We can add detection for both config file paths, but I'd need to verify that by debian/ubuntu people.

**Comment by kdave** [comment]
Closing. Feel free to open a new issue if there are any further prolbems on Ubuntu.

**Pull request closed without merging**
