### PR TITLE
Add support for systemd timers.

### PR DESCRIPTION
**Pull request by comio**
Hi,

I'm using systemd timers instead cronjob. I prefer to avoid mixed solution cron/systemd on my system and I created this trivial patch.

I hope to be useful.

ciao

luigi

### CODE REVIEW

**Comment by Djelibeybi** [comment]
Looks like `btrfs-scrub.service` is an unmodified copy of `btrfs-trim.service`. :)

**Comment by comio** [comment]
My mistake

**Comment by comio** [comment]
Hi @kdave and @Djelibeybi,

I rewrite the timers and moved the management code into -refresh-cron.sh following suggestion from @madmartin (gentoo).
I cannot validate .spec file because I'm not a rpm user, please check yourself if you can.

I hope in your feedback.

ciao

luigi

**Comment by comio** [comment]
any comment?

ciao

luigi

**Comment by comio** [comment]
Continue on #35

**Pull request closed without merging**
