### PR TITLE
Balance period improvements (fate#325529); Removing python dependency (jsc#SLE-4130).

### PR DESCRIPTION
**Pull request by jeffmahoney**
This PR changes the periods for balance to "5 10" for data and "3" for metadata.  It also adds support for systemd.time(7) calendar event format periods and ensures they're not allowed on cron-base systems.

### CODE REVIEW

**Comment by jeffmahoney** [comment]
Keep this one on hold for a bit. In testing, it seems like it's rejecting the calendar format anyway.

**Comment by jeffmahoney** [comment]
Ok, it's not a bug in this PR. The systemd.path stuff seems to be racy.  I think it's possible for the event to be called while e.g. vim is still writing out the file, so it gets an empty sysconfig file and fills in empty timer OnCalendar values.

**Comment by jeffmahoney** [comment]
This should be set for inclusion now.

**Comment by kdave** [comment]
I've merged the README (with update about improvements in 5.2+ kernel), time spec as calendar event, and the shell plugn. I'll keep the .py version for now, and the null byte in the script has been replaced by `$'\0' so it does not appear as a binary file.

The remaining part are the balance filter defaults, I need to reread the past discussions, but in general reducing the numbers is agreed.

**Comment by kdave** [comment]
Balance usage filters have been updated, no more issues left, closing.

**Pull request closed without merging**
