### PR TITLE
Debian support

### PR DESCRIPTION
**Pull request by euidzero**
Hi,

 Small changes to support debian (Jessie). Namely:

- install config /etc/default/
- do not use .sh in symlinks names in /etc/cron.*
- simple install script

Hope it helps

### CODE REVIEW

**Comment by kdave** [comment]
I'm not sure how much I should bother you with nitpicks, but here's what I'd like to see fixed:
* patch 1 add newline after the added code
* patch 4 can be folded into 3

I can do that myself but then I can't merge the pull request directly. Let me know if you're fine with me fixing the patches.

**Comment by kdave** [comment]
```diff
--- a/btrfsmaintenance-refresh-cron.sh
+++ b/btrfsmaintenance-refresh-cron.sh
@@ -33,17 +33,18 @@ fi
 if [ -f /etc/default/btrfsmaintenance ]; then
     . /etc/default/btrfsmaintenance
 fi
+
 refresh_period() {
        EXPECTED="$1"
        SCRIPT="$2"
        echo "Refresh script $SCRIPT for $EXPECTED"

        for PERIOD in daily weekly monthly; do
-               #NB Debian does not allow filenames with dots in /etc/cron.*
+               # NOTE: debian does not allow filenames with dots in /etc/cron.*
                LINK="${SCRIPT%.*}"
                FILE="/etc/cron.$PERIOD/$LINK"
                if [ "$PERIOD" = "$EXPECTED" ]; then
-                        ln -sf "$SCRIPTS/$SCRIPT" "$FILE"
+                       ln -sf "$SCRIPTS/$SCRIPT" "$FILE"
                else
                        rm -f "$FILE"
                fi

```

or see branch euidzero-pull-9-fixed

**Comment by euidzero** [comment]
Le lun. 22 févr. 2016 à 16:45, kdave <notifications@github.com> a écrit :

> I'm not sure how much I should bother you with nitpicks, but here's what
> I'd like to see fixed:
>
>    - patch 1 add newline after the added code
>    - patch 4 can be folded into 3
>
> I can do that myself but then I can't merge the pull request directly. Let
> me know if you're fine with me fixing the patches.
>
Hi,

 Feel free to fix with your own coding standard :)

**Comment by kdave** [comment]
Ok, merged the fixed branch.

**Pull request closed without merging**
