### PR TITLE
btrfs-defrag.sh: use proper unit for defrag command

### PR DESCRIPTION
**Pull request by fcrozat**

### CODE REVIEW

**Comment by kdave** [comment]
There's no difference, m and M work the same and it's documented. Am I missing something?

**Comment by fcrozat** [comment]
the command doesn't work on Leap 42.2 at all with m

**Comment by kdave** [comment]
Works for me. I've compiled from 42.2 sources and defragmented a file, using -t 32m. No complaints about syntax and the resulting extent sizes match the target size. Please post more details.

**Comment by fcrozat** [comment]
ok, found: I had also BTRFS_DEFRAG_MIN_SIZE=+1m in /etc/sysconfig/btrfsmaintenance which was not migrated to +1M when the fix was done on btrfsmaintenance (package was installed before).

Therefore, this fix is not strictly needed (but it looks nicer, to go with the previous fix for find ;)

**Comment by kdave** [comment]
I'd like to close this issue, the lowercase variant has been fixed in v0.2 and we haven't seen any other reports so I don't think we need a tool to fixup the configuration.

**Pull request closed without merging**
